import type { Metadata } from 'next';
import './globals.css';
import Hero from '@/components/Layout/Sections/Hero';
import PhotographySection from '@/components/Layout/Sections/PhotographySection';
import VideoGraphySection from '@/components/Layout/Sections/VideoGraphySection';
import TestimonialsSection from '@/components/Layout/Sections/TestimonialsSection';
import MyServicesSection from '@/components/Layout/Sections/MyServicesSection';
import Footer from '@/components/Layout/Footer';
import BurgerMenu from '@/components/UI/BurgerMenu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function
  RootLayout({
               children
             }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <div id="form"></div>
    {children}
    {/*<GoToTheTopBtn />*/}
    <BurgerMenu />
    <div className={`w-full`}>
      <div className={`sm:h-[120%] bg-hero mb-16 pb-24`}>
        <Hero />
      </div>
      <main>
        <PhotographySection />
        <VideoGraphySection />
        <TestimonialsSection />
        <MyServicesSection />
      </main>
      <Footer />
    </div>
    </body>
    </html>
  );
}
